[package]
name = "bitreserve"
version = "0.0.1"
authors = ["Miguel Palhas <mpalhas@gmail.com>"]

[dependencies]
"rustc-serialize" = "*"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
